// mkfontdata: analyzes the 6502's fontdef.txt into a header, 6502font.h, containing info about which glyphs are supported

#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <stdlib.h>

struct entry {
	uint32_t unicode : 24;
	uint8_t translit;
};

struct entry *entries;
int nentry, nalloc;

void add(uint32_t unicode, int translit) {
	if(!unicode) return; // Don't put a 0 into the table, we need it as a terminator
	
	if(nentry == nalloc) {
		nalloc = 2 * nalloc + 8;
		entries = realloc(entries, nalloc * sizeof(struct entry));
		memset(entries + nentry, 0, (nalloc - nentry) * sizeof(struct entry));
	}
	
	entries[nentry].unicode = unicode;
	entries[nentry++].translit = translit;
}

int main() {
	char buf[64];
	uint32_t unicode;
	int found;
	char ignored;
	
	while(fgets(buf, sizeof(buf), stdin)) {
		found = sscanf(buf, "+%x \" %c", &unicode, &ignored);
		if(found == 2) { // Found both number and character
			add(unicode, 1);
		} else if(found == 1) { // Only number, not character
			add(unicode, 0);
		}
	}
	
	printf("// Automatically generated by mkfontdata\n");
	printf("static const uint32_t unicode_in_font[] = { ");
	for(int i=0; i<nentry; i++) {
		printf("0x%04x, ", entries[i].unicode);
	}
	printf("0 };\n");
	printf("static const uint32_t unicode_has_translit[] = { ");
	for(int i=0; i<nentry; i++) {
		if(!entries[i].translit) continue;
		printf("0x%04x, ", entries[i].unicode);
	}
	printf("0 };\n");
}
