// mkfontdata: analyzes the 6502's fontdef.txt into a header, 6502font.h, containing info about which glyphs are supported

#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <stdlib.h>

struct entry {
	uint32_t unicode : 24;
	uint8_t glyph : 1;
	uint8_t translit : 1;
};

struct entry *entries;
int nentry, nalloc;

void add(uint32_t unicode, int glyph, int translit) {
	if(!unicode) return; // Don't put a 0 into the table, we need it as a terminator
	
	if(nentry == nalloc) {
		nalloc = 2 * nalloc + 8;
		entries = realloc(entries, nalloc * sizeof(struct entry));
		memset(entries + nentry, 0, (nalloc - nentry) * sizeof(struct entry));
	}
	
	entries[nentry].unicode = unicode;
	entries[nentry].glyph = glyph;
	entries[nentry++].translit = translit;
}

inline int is_glyph_char(char in) {
	return in == '#' || in == '.';
}

int main() {
	char buf[64];
	int32_t unicode;
	int found;
	char ignored;
	int32_t pending_uni = -1;
	int pending_translit;
	
	while(fgets(buf, sizeof(buf), stdin)) {
		found = sscanf(buf, "+%x \" %c", &unicode, &ignored);
		
		if(found == 0) { // Not the start of a new entry, but could be continuing an old one
			if(pending_uni == -1) continue; // Nothing worth checking now
			if(is_glyph_char(buf[0]) && is_glyph_char(buf[1]) && is_glyph_char(buf[2])) {
				add(pending_uni, 1, pending_translit);
				pending_uni = -1;
			}
		} else {
			if(pending_uni != -1) add(pending_uni, 0, pending_translit); // No glyph was found
			pending_uni = unicode;
			pending_translit = (found > 1);
		}
	}
	
	if(pending_uni != -1) add(pending_uni, 0, pending_translit); // In case of no newline at end of file
	
	printf("// Automatically generated by mkfontdata\n");
	printf("static const uint32_t unicode_in_font[] = { ");
	for(int i=0; i<nentry; i++) {
		if(!entries[i].glyph) continue;
		printf("0x%04x, ", entries[i].unicode);
	}
	printf("0 };\n");
	printf("static const uint32_t unicode_has_translit[] = { ");
	for(int i=0; i<nentry; i++) {
		if(!entries[i].translit) continue;
		printf("0x%04x, ", entries[i].unicode);
	}
	printf("0 };\n");
}
