# VERY IMPORTANT: This should be a version of gosling compiled with Dialog 1a/01 or earlier, ensuring that it uses version 0.x of the Å-machine
# The purpose is to ensure the interpreters can still handle old story files

include ../common.mk